# Generated by Django 5.2 on 2025-04-03 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_diary', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['class_name', 'last_name', 'first_name']},
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['class_name', 'last_name', 'first_name'], name='digital_dia_class_n_be9447_idx'),
        ),
    ]
